name: vercel deployment

on:
  push:
    branches:
      - main

env:
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}

jobs:
  deployment-production:
    runs-on: ubuntu-latest
    environment: deployment
    env:
      ENV_SECRETS: ${{ secrets.ENV_SECRETS }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: install vercel CLI
        run: npm i -g vercel
      - name: pull environment information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: vercel build
        run: |
          echo "$ENV_SECRETS" >> .env.local
          vercel build --prod --token=${{secrets.VERCEL_TOKEN}}
      - name: Deploy to vercel
        run: vercel deploy --prebuilt --prod --token=${{secrets.VERCEL_TOKEN}}
